server:
  port: 8082

spring.application.name: storage

eureka:
  instance:
      hostname: storage
  client:
      registerWithEureka: false
      fetchRegistry: false
      server:
        waitTimeInMsWhenSyncEmpty: 0


